name: 'Assign Issue'
on:
  issue_comment:
    types: [created]

jobs:
  assign_to_user:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to user
      uses: actions/github-script@v3
      with:
        script: |
          const commentBody = context.payload.comment.body;
          const issue = context.payload.issue;
          if (commentBody.trim() === "/assignme" || commentBody.trim() === "/assign me") {
            const assignee = context.payload.comment.user.login;
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: [assignee]
            })
          }
